server:
  port: 7788
spring:
  application:
    name: lemon-backend-security
  datasource:
    url: jdbc:mysql://localhost:3306/study?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 520.hate
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
